<?php
define( 'SBI_ENCRYPTION_KEY', '5WYt6!BY1!dcywGR(07oLhKZl5DDQ&S)A6lSzMvDSQioC8trLR&c3VJNmmwjBbP1' );

define( 'SBI_ENCRYPTION_SALT', 'lFg5l0Kn0rZkyXbnsSh0S%trZ2t*fEMsP$t$f2wcoYco8Zk6Hj%%JVXTJnK6Yng(' );

/** Enable W3 Total Cache */
define('WP_CACHE', true); // Added by W3 Total Cache


/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';

